### ISSUE TITLE
数据集没有找到

### ISSUE THREAD

**Issue by woshiawang** [sunnweiwei/MixCL#1]
你好，我根据网站下载的数据集和代码不匹配，你可以发一下数据集的安装包链接吗？非常感谢

**Comment by sunnweiwei** [comment]
数据处理代码：https://github.com/sunnweiwei/GenKS/blob/main/process_wizard.py
处理之后的数据：https://drive.google.com/file/d/1ccPi-f8x_yqvVkGVN8rnNkkevrVFyY3D/view?usp=drive_link
希望对您有帮助:)
